### ISSUE TITLE
Bro, can you port the code to Arduino and add support for rs232? This way many old UPS will be useful, thank you

### ISSUE THREAD

**Issue by zrwd01** [ludoux/esp32-nut-server-usbhid#1]
Bro, can you port the code to Arduino and add support for rs232? This way many old UPS will be useful, thank you
大佬,能不能移植一下代码到arduino上,另外也增加一下rs232的支持?这样许多老ups就有用武之地了,多谢

**Comment by ludoux** [comment]
Sorry, maybe there is no way to achieve it here.  Because I don’t have an Arduino device or RS232 related equipment, sorry.

很抱歉，可能都没法…因为我没有Arduino 设备，也没有RS232相关的设备，sorry啦
